### ISSUE TITLE
Root Folder Issue - CI pipeline

### ISSUE THREAD

**Issue by ghost** [Snowflake-Labs/sfquickstarts#65]
**Describe the bug**
I'm trying to follow the steps on snowflake guide page and set up Azure DevOps CI pipeline.

https://guides.snowflake.com/guide/devops_dcm_schemachange_azure_devops/index.html?index=..%2F..index#5

**Root Folder Issue**
I have set up the Project_Folder parameter to $(System.DefaultWorkingDirectory) and I receive the following error:
ValueError: Invalid root folder: /home/vsts/work/1/s/azure-pipeline-test.

Altough my root folder seems to be correct:
![image](https://user-images.githubusercontent.com/59688582/121945667-514ed580-cd54-11eb-8fdb-4f390c6b04c7.png)

Here is my yml:
![image](https://user-images.githubusercontent.com/59688582/121945951-a8ed4100-cd54-11eb-9b53-b8e1f88b34c7.png)

When I delete the "/azure-test-pipeline from root below, the CI pipeline runs without errors, creates table in snowflke but doesn't insert anything there nor runs SQL scripts.

**Additional context**
IMHO the root folder automatically adds "/home/vsts/work/1/s" which is a bit confusing for me..

**Comment by sfc-gh-jhansen** [comment]
Hi there @DA-JLL, thanks for reaching out with feedback. I don't see an obvious root cause here, but I do notice that you're not following the guide exactly (based off your folder and branch naming). I would ask that you follow the guide and exactly and please let me know what issues you run into. Thanks!
